/*******************************************************************************
* FILENAME: project.h
* 
* PSoC Creator  3.2
*
* DESCRIPTION:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "QuadDec_2.h"
#include "QuadDec_1.h"
#include "M1QA.h"
#include "M1QA_aliases.h"
#include "M1QB.h"
#include "M1QB_aliases.h"
#include "M2QA.h"
#include "M2QA_aliases.h"
#include "M2QB.h"
#include "M2QB_aliases.h"
#include "Clock_1.h"
#include "UART.h"
#include "UART_SPI_UART.h"
#include "UART_PINS.h"
#include "UART_SPI_UART_PVT.h"
#include "UART_PVT.h"
#include "UART_BOOT.h"
#include "BIN2_1.h"
#include "BIN2_1_aliases.h"
#include "AIN2_1.h"
#include "AIN2_1_aliases.h"
#include "BIN1_1.h"
#include "BIN1_1_aliases.h"
#include "AIN1_1.h"
#include "AIN1_1_aliases.h"
#include "PWM_R.h"
#include "BIN2_2.h"
#include "BIN2_2_aliases.h"
#include "AIN2_2.h"
#include "AIN2_2_aliases.h"
#include "Clock_2.h"
#include "BIN1_2.h"
#include "BIN1_2_aliases.h"
#include "AIN1_2.h"
#include "AIN1_2_aliases.h"
#include "DIR_CONTROL.h"
#include "PWM_F.h"
#include "cursense1.h"
#include "cursense1_aliases.h"
#include "cursense2.h"
#include "cursense2_aliases.h"
#include "ADC.h"
#include "Mode1.h"
#include "Mode1_aliases.h"
#include "Mode2.h"
#include "Mode2_aliases.h"
#include "Power1.h"
#include "Power1_aliases.h"
#include "Power2.h"
#include "Power2_aliases.h"
#include "UART_SCBCLK.h"
#include "UART_tx.h"
#include "UART_tx_aliases.h"
#include "UART_rx.h"
#include "UART_rx_aliases.h"
#include "ADC_IRQ.h"
#include "ADC_intClock.h"
#include "core_cm0_psoc4.h"
#include "core_cm0.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"
#include "CyLFClk.h"

/*[]*/

